title: Research Software Hour
#email: your-email@example.com
description: >-
  Research Software Hour is a online show discussing scientific
  computing and research software designed to provide the informal
  kind of skills you don't learn academically.
baseurl: "" # the subpath of your site (leading slash), e.g. /blog
url: "https://researchsoftwarehour.github.io"
show_excerpts: true

logo: /assets/images/logo-hashbang.png
logo-twitter: /assets/images/logo-hashbang-big.png
favicon: /assets/images/logo-hashbang.ico

minima:
  date_format: "%-d %b %Y"
  social_links:
    twitter: __radovan
    github: researchsoftwarehour
    hackmd: "@researchsoftwarehour"
    extra:
      - url: https://github.com/bast/
        name: "bast"
        icon: github
      - url: https://github.com/rkdarst/
        name: "rkdarst"
        icon: github

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-remote-theme
# We can switch back to regular theme once >2.5.1 is released
#theme: minima
remote_theme: jekyll/minima

future: true
