title: Research Software Hour
#email: your-email@example.com
description: >-
  Research Software Hour is a online show discussing scientific
  computing and research software designed to provide the informal
  kind of skills you don't learn academically.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://researchsoftwarehour.github.io"

show_excerpts: true

twitter_username: bast
#github_username:  jekyll

minima:
  date_format: "%-d %b %Y"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
